# Configuration du serveur
server.port=8081
spring.application.name=chatbot

# Configuration JWT
jwt.secret=your_real_key
jwt.expiration=86400000

# API Groq (utilisation directe sans Spring AI)
groq.api.key=your_real_key

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/g11_education?useUnicode=true&characterEncoding=UTF-8&stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=walid
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool Settings
spring.datasource.hikari.connectionInitSql=SET NAMES 'UTF8'
spring.datasource.hikari.connectionTestQuery=SELECT 1

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8

# Encodage Spring Boot
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Encodage JSON
spring.jackson.encoding=UTF-8
spring.jackson.default-property-inclusion=non_null

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.example.demo=DEBUG